import { Button, VerticalBox, HorizontalBox, SpinBox, ProgressIndicator } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <int> workTime: 25;
    in property <int> playTime: 25;
    in-out property <int> remainingTime: 0;
    in-out property <bool> showprogress;
    callback update-workTime(int);
    callback update-playTime(int);
    callback startTimer();
    callback remainingTimeChanged(int);
    max-width: 400px;
    max-height: 150px;
    
    // Define the window properties
    title: "Pomodoro Timer";
    VerticalBox {
        Text {
            text: "Pomodoro Timer";
            font-size: 20px;
            font-weight: 500;
            horizontal-alignment: TextHorizontalAlignment.center;
           
            letter-spacing: 1px;
            ProgressIndicator {

                width: showprogress ? 95% : 0%;
                height: 85%;
                opacity: 0.9;
                progress: remainingTime / 100 ;
                z: 1;
                animate width{
                    duration: 0.5s;easing: ease-out-back;
                     
                }
            }}
        HorizontalBox {
            VerticalBox {
                Button {
                    text: "START";
                    clicked => {
                        startTimer();
                        root.showprogress=!root.showprogress;
                        debug("Start button clicked");
                    }}}
            VerticalBox {
                Text {
                    font-size: 18px;
                    font-weight: 600;
                    horizontal-alignment: TextHorizontalAlignment.center;
                    text: "Play";
                }
                SpinBox {
                    minimum: 0;
                    maximum: 60;
                    value: playTime;
                    edited(playTime) => {
                        update-playTime(playTime);
                    }}}
            VerticalBox {
                Text {
                    font-size: 18px;
                    font-weight: 600;
                    horizontal-alignment: TextHorizontalAlignment.center;
                    text: "Work";
                }
                SpinBox {
                    minimum: 0;
                    maximum: 60;
                    value: workTime;
                    edited(workTime) => {
                        update-workTime(workTime);
                    }}}
        }
    }
}